kind: Pod
apiVersion: v1
metadata:
  name: environment
spec:
  containers:
  - name: nginx
    image: nginx 
    env:
    - name: course
      value: "K8"
    - name: duration
      value: '20hrs'    