kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: efs-dynamic
reclaimPolicy: Retain  
provisioner: efs.csi.aws.com
parameters:
  provisioningMode: efs-ap
  fileSystemId: fs-0130c5b8dc3c98055
  directoryPerms: "700"
  basePath: "/expense"
---
apiVersion: v1
kind: Pod
metadata:
  name: efs-dynamic
  labels:
    purpose: efs-dynamic
spec:
  containers:
    - name: nginx
      image: nginx
      volumeMounts:
        - name: persistent-storage
          mountPath: /usr/share/nginx/html
  volumes:
    - name: persistent-storage
      persistentVolumeClaim:
        claimName: efs-dynamic
---
apiVersion: v1
kind: Service
metadata:
  name: efs-dynamic
spec:
  selector:
    purpose: efs-dynamic
  ports:
  - protocol: TCP
    port: 80#service-port
    targetPort: 80


